# Generated by Django 4.2.5 on 2023-11-14 19:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="the timestamp indicating when the shopping cart was created ",
                        verbose_name="created at ",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        help_text="the time stamp indicating when the shopping cart was last updated ",
                        verbose_name="updated at ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        help_text="the quantity of the products in this cart item ",
                        verbose_name="quantity ",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        help_text="The shopping cart to which this item belongs ",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="cart.cart",
                        verbose_name="shopping cart ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The prosuct included in this cart item ",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="products.productmodel",
                        verbose_name="product ",
                    ),
                ),
            ],
        ),
    ]
