# Generated by Django 4.2.1 on 2023-12-05 09:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Session key for anonymous user carts",
                        max_length=40,
                        null=True,
                        verbose_name="session key",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The timestamp indicating when the shopping cart was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The timestamp indicating when the shopping cart was last updated",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True, help_text="Indicates if the cart is active"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        help_text="The user to whom this shopping cart belongs",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Session key for anonymous user carts",
                        max_length=40,
                        null=True,
                        verbose_name="session key",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        help_text="The quantity of the products in this cart item",
                        verbose_name="quantity",
                    ),
                ),
                (
                    "cart",
                    models.ForeignKey(
                        blank=True,
                        help_text="The shopping cart to which this item belongs",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="cart.cart",
                        verbose_name="shopping cart",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product included in this cart item",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cart_items",
                        to="products.productmodel",
                        verbose_name="product",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Checkout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp indicating when the checkout was created",
                        verbose_name="created at",
                    ),
                ),
                (
                    "order_total",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Total cost of the order",
                        max_digits=10,
                        verbose_name="order total",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Completed", "Completed"),
                            ("Failed", "Failed"),
                        ],
                        default="Pending",
                        help_text="Status of the payment",
                        max_length=100,
                        verbose_name="payment status",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Transaction ID for the payment",
                        max_length=100,
                        null=True,
                        verbose_name="transaction id",
                    ),
                ),
                (
                    "payment_option",
                    models.CharField(
                        choices=[
                            ("credit_card", "Credit Card"),
                            ("visa", "Visa"),
                            ("debit_card", "Debit Card"),
                        ],
                        default="credit_card",
                        max_length=100,
                        verbose_name="payment option",
                    ),
                ),
                ("delivery_address", models.TextField(null=True)),
                (
                    "user",
                    models.ForeignKey(
                        help_text="The user who is checking out",
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        help_text="The quantity of the product in this order item",
                        verbose_name="quantity",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Price of the product",
                        max_digits=10,
                        verbose_name="price",
                    ),
                ),
                (
                    "cart_item",
                    models.ForeignKey(
                        blank=True,
                        help_text="The cart item that was ordered",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cart.cartitem",
                        verbose_name="cart item",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        help_text="The checkout order to which this item belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_items",
                        to="cart.checkout",
                        verbose_name="order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The product included in this order item",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productmodel",
                        verbose_name="product",
                    ),
                ),
            ],
        ),
    ]
