# Generated by Django 4.2.5 on 2023-11-18 10:29

from decimal import Decimal
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Oderitem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.IntegerField(
                        default=1,
                        help_text="the quantity of the product in this order item ",
                        verbose_name="quantity",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        help_text="the price of a single unit of the product in this orde ritem ",
                        max_digits=1000000,
                        verbose_name="price ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The timestamp indicating when the order was created ",
                        verbose_name="created at ",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        help_text="the timestamp indicating when the order was last updated ",
                        verbose_name="updated at ",
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="the total amount for the order ",
                        max_digits=100000,
                        verbose_name="total amount ",
                    ),
                ),
            ],
        ),
    ]
