# Generated by Django 4.2.5 on 2023-11-18 10:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "search_query",
                    models.CharField(
                        help_text="the search query enterd by the user ",
                        max_length=255,
                        verbose_name="search query",
                    ),
                ),
                (
                    "search_filters",
                    models.JSONField(
                        help_text="Aditional filters applied to the search query ",
                        null=True,
                        verbose_name="search filters ",
                    ),
                ),
                (
                    "search_timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="The timestamp which the search was performed ",
                        verbose_name="search timestamp ",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        help_text="The producr associatd with the search data",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_searchs",
                        to="products.productmodel",
                        verbose_name="product ",
                    ),
                ),
            ],
        ),
    ]
