# Generated by Django 4.2.7 on 2023-11-16 09:43

import datetime
from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="none",
                        help_text="The name of the shoe produc",
                        max_length=255,
                        verbose_name="Product Name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="a detailed discription of the shoe product ",
                        null=True,
                        verbose_name="Product Discription",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.0"),
                        help_text="The price of the shoe product ",
                        max_digits=50,
                        verbose_name="Product Price ",
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        default=0,
                        help_text="The available quantity of the shoe product",
                        verbose_name="product stock ",
                    ),
                ),
                (
                    "images",
                    models.ImageField(
                        help_text="An image representing the shoe product ",
                        max_length=255,
                        null=True,
                        upload_to="productmodel/images/",
                        verbose_name="Product Image ",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        default=datetime.date.today,
                        help_text="the timestamp indicating when the shoe product was created ",
                        verbose_name="created at ",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        help_text="The timestap indicating when the shoe product was last updated ",
                        verbose_name="updated at ",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        help_text="the ategory to which this produc belongs",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="categories",
                        to="products.productmodel",
                        verbose_name="category ",
                    ),
                ),
            ],
        ),
    ]
