# Generated by Django 4.2.5 on 2023-11-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="the title of the blog post ",
                        max_length=255,
                        verbose_name="title",
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        help_text="The main content of the blog post",
                        verbose_name="Content",
                    ),
                ),
                (
                    "pub_date",
                    models.DateTimeField(
                        help_text="the date when the blog post ",
                        verbose_name="publication date ",
                    ),
                ),
            ],
        ),
    ]
