# Generated by Django 4.2.5 on 2023-11-22 16:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_blogpost_pub_date_alter_blogpost_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="pub_date",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="the date when the blog post was published",
                verbose_name="publication date",
            ),
        ),
        migrations.AlterField(
            model_name="blogpost",
            name="title",
            field=models.CharField(
                help_text="the title of the blog post ",
                max_length=255,
                verbose_name="title",
            ),
        ),
    ]
