# Generated by Django 4.2.7 on 2023-11-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Notificationapp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "messages",
                    models.TextField(
                        help_text="The content of the notification message",
                        verbose_name="message",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(
                        default=False,
                        help_text="indicates whether the user has read the notification ",
                        verbose_name="is read",
                    ),
                ),
                (
                    "notification_timestamp",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The timestamp whhen the notifaction was created",
                        verbose_name="notification timestamp ",
                    ),
                ),
            ],
        ),
    ]
