# Generated by Django 4.2.5 on 2023-11-19 13:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_profile_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                default="",
                help_text="User's first name",
                max_length=255,
                verbose_name="first Name",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(
                default="",
                help_text="User's last name",
                max_length=255,
                verbose_name=" last Name",
            ),
        ),
    ]
