# Generated by Django 4.2.5 on 2023-11-19 14:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_first_name_user_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
    ]
