# Generated by Django 4.2.7 on 2023-12-05 00:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Wishlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wishlist_id", models.CharField(blank=True, max_length=250)),
                ("date_added", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "Wishlist",
                "ordering": ["date_added"],
            },
        ),
        migrations.AlterModelTable(
            name="wishlistitem",
            table="WishlistItem",
        ),
    ]
